spring.application.name=erp

# Conexão com o Banco de Dados na Nuvem (Render)
spring.datasource.url=jdbc:postgresql://dpg-d94d2v0js32c73e7gl5g-a.oregon-postgres.render.com:5432/borges_erp
spring.datasource.username=borges_erp_user
spring.datasource.password=OP4uFn3PvZ1NEaQjmDIhnMIdqnD0zf3j

# Configurações do Hibernate (Cria as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true