spring.application.name=erp

# Credenciais de acesso ao PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/borges_erp
spring.datasource.username=postgres
spring.datasource.password=159696
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações de tradução (Hibernate/JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
